"""First

Revision ID: 143e57226aca
Revises: 
Create Date: 2023-07-20 17:04:43.306526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143e57226aca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
